name: docker-tomcat-exposed

on:
  push:
    branches: none #[ "main" ]
  pull_request:
    branches: none #[ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker-tomcat-exposed:$(date +%s)
